"""
Prediction API for the Siege ML Live Round Predictor.

Wraps src.predict.RoundPredictor as an HTTP service so a live app (or
anything else) can get a win probability with a single request instead
of shelling out to a script. Also exposes lookup endpoints for valid
operators/maps/sites so a front end can build dropdowns without
duplicating that logic or hardcoding a list that can drift, like the
CLI's original map bug did.

Run from the SWP/ project root:
    uvicorn app.api:app --reload --port 8000

Then, e.g.:
    curl http://localhost:8000/maps
    curl http://localhost:8000/sites/CLUB_HOUSE
    curl -X POST http://localhost:8000/predict -H "Content-Type: application/json" -d '{
        "attackers": ["THERMITE", "HIBANA", "BUCK", "ASH", "TWITCH"],
        "defenders": ["BANDIT", "MUTE", "JAGER", "MIRA", "SMOKE"],
        "map_name": "CLUB_HOUSE",
        "site": "CCTV_ROOM"
    }'

Interactive docs (auto-generated by FastAPI) are at:
    http://localhost:8000/docs
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from fastapi import FastAPI, HTTPException  # noqa: E402
from pydantic import BaseModel, field_validator  # noqa: E402

from src.config import ATTACK_OPERATORS, DEFENSE_OPERATORS  # noqa: E402
from src.predict import RoundPredictor  # noqa: E402

app = FastAPI(
    title="Siege ML Live Round Predictor API",
    description="Predicts attack/defense win probability from pre-round operator, map, and site selections.",
    version="0.1.0",
)

# Loaded once at startup, reused across requests — avoids reloading the
# model and joblib files on every call.
predictor = RoundPredictor()


class PredictionRequest(BaseModel):
    attackers: list[str]
    defenders: list[str]
    map_name: str
    site: str = ""

    @field_validator("attackers")
    @classmethod
    def validate_attackers(cls, v):
        if len(v) != 5:
            raise ValueError(f"Expected exactly 5 attackers, got {len(v)}")
        unknown = [op for op in v if op.upper() not in ATTACK_OPERATORS]
        if unknown:
            raise ValueError(f"Unknown attacker(s): {unknown}. Valid: {ATTACK_OPERATORS}")
        return [op.upper() for op in v]

    @field_validator("defenders")
    @classmethod
    def validate_defenders(cls, v):
        if len(v) != 5:
            raise ValueError(f"Expected exactly 5 defenders, got {len(v)}")
        unknown = [op for op in v if op.upper() not in DEFENSE_OPERATORS]
        if unknown:
            raise ValueError(f"Unknown defender(s): {unknown}. Valid: {DEFENSE_OPERATORS}")
        return [op.upper() for op in v]


class PredictionResponse(BaseModel):
    attack_win_probability: float
    defense_win_probability: float


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/operators")
def operators():
    return {"attackers": ATTACK_OPERATORS, "defenders": DEFENSE_OPERATORS}


@app.get("/maps")
def maps():
    return {"maps": predictor.encoder.valid_maps()}


@app.get("/sites/{map_name}")
def sites(map_name: str):
    map_name = map_name.upper()
    if map_name not in predictor.encoder.valid_maps():
        raise HTTPException(
            status_code=404,
            detail=f"Unknown map: {map_name!r}. Valid maps: {predictor.encoder.valid_maps()}",
        )
    return {"map": map_name, "sites": predictor.encoder.valid_sites(map_name)}


@app.post("/predict", response_model=PredictionResponse)
def predict(request: PredictionRequest):
    map_name = request.map_name.upper()
    if map_name not in predictor.encoder.valid_maps():
        raise HTTPException(
            status_code=400,
            detail=f"Unknown map: {map_name!r}. Valid maps: {predictor.encoder.valid_maps()}",
        )

    site = request.site.upper()
    valid_sites = predictor.encoder.valid_sites(map_name)
    if site and valid_sites and site not in valid_sites:
        raise HTTPException(
            status_code=400,
            detail=f"Unknown site {site!r} for map {map_name!r}. Valid sites: {valid_sites}",
        )

    try:
        result = predictor.predict(request.attackers, request.defenders, map_name, site)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    return result
